[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calcster"
version = "0.1.0"
description = "Web resource with collection of calculators"
authors = [{name = "HarryWhen"}]
dependencies = [
    "fastapi==0.117.1",
]
